import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/ui/header";
import { SideMenu } from "@/components/ui/sideMenu";
import { Footer } from "@/components/ui/footer";
import "../normalize.css";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="device">
            <div className="container">
              <Header />
              {children}
              <Footer />
              <SideMenu />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
